//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mybatis_Plus_Generator.Langs {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Lang {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Lang() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Mybatis_Plus_Generator.Langs.Lang", typeof(Lang).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 确认 的本地化字符串。
        /// </summary>
        public static string Accept {
            get {
                return ResourceManager.GetString("Accept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 追加连接字符串 的本地化字符串。
        /// </summary>
        public static string addConnectionProperty {
            get {
                return ResourceManager.GetString("addConnectionProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 添加排除 的本地化字符串。
        /// </summary>
        public static string addExclude {
            get {
                return ResourceManager.GetString("addExclude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 添加字段前缀 的本地化字符串。
        /// </summary>
        public static string addFieldPrefix {
            get {
                return ResourceManager.GetString("addFieldPrefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 添加字段后缀 的本地化字符串。
        /// </summary>
        public static string addFieldSuffix {
            get {
                return ResourceManager.GetString("addFieldSuffix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 添加包含 的本地化字符串。
        /// </summary>
        public static string addInclude {
            get {
                return ResourceManager.GetString("addInclude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 添加表前缀 的本地化字符串。
        /// </summary>
        public static string addTablePrefix {
            get {
                return ResourceManager.GetString("addTablePrefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 添加表后缀 的本地化字符串。
        /// </summary>
        public static string addTableSuffix {
            get {
                return ResourceManager.GetString("addTableSuffix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 作者 的本地化字符串。
        /// </summary>
        public static string author {
            get {
                return ResourceManager.GetString("author", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 在输出文件前 的本地化字符串。
        /// </summary>
        public static string beforeOutputFile {
            get {
                return ResourceManager.GetString("beforeOutputFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 构造器 的本地化字符串。
        /// </summary>
        public static string Builder {
            get {
                return ResourceManager.GetString("Builder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 无法删除固定配置 的本地化字符串。
        /// </summary>
        public static string Can_not_delete_fixed_config {
            get {
                return ResourceManager.GetString("Can_not_delete_fixed_config", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 取消 的本地化字符串。
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 中文 的本地化字符串。
        /// </summary>
        public static string Chinese__China_ {
            get {
                return ResourceManager.GetString("Chinese (China)", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 注释日期 的本地化字符串。
        /// </summary>
        public static string commentDate {
            get {
                return ResourceManager.GetString("commentDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 配置名称已存在 的本地化字符串。
        /// </summary>
        public static string Config_name_exists {
            get {
                return ResourceManager.GetString("Config name exists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 配置名称 的本地化字符串。
        /// </summary>
        public static string ConfigName {
            get {
                return ResourceManager.GetString("ConfigName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 控制器 的本地化字符串。
        /// </summary>
        public static string controller {
            get {
                return ResourceManager.GetString("controller", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 控制器模板 的本地化字符串。
        /// </summary>
        public static string controllerTemplate {
            get {
                return ResourceManager.GetString("controllerTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 自定义文件 的本地化字符串。
        /// </summary>
        public static string customFile {
            get {
                return ResourceManager.GetString("customFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 自定义映射 的本地化字符串。
        /// </summary>
        public static string customMap {
            get {
                return ResourceManager.GetString("customMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 数据库查询类 的本地化字符串。
        /// </summary>
        public static string databaseQueryClass {
            get {
                return ResourceManager.GetString("databaseQueryClass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 数据源配置 的本地化字符串。
        /// </summary>
        public static string DataSourceConfig {
            get {
                return ResourceManager.GetString("DataSourceConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 时间类型 的本地化字符串。
        /// </summary>
        public static string dateType {
            get {
                return ResourceManager.GetString("dateType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 查询字符串 的本地化字符串。
        /// </summary>
        public static string dbQuery {
            get {
                return ResourceManager.GetString("dbQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 禁用 的本地化字符串。
        /// </summary>
        public static string disable {
            get {
                return ResourceManager.GetString("disable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 禁止打开目录 的本地化字符串。
        /// </summary>
        public static string disableOpenDir {
            get {
                return ResourceManager.GetString("disableOpenDir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 禁用服务接口 的本地化字符串。
        /// </summary>
        public static string disableServiceInterface {
            get {
                return ResourceManager.GetString("disableServiceInterface", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 禁用Sql过滤 的本地化字符串。
        /// </summary>
        public static string disableSqlFilter {
            get {
                return ResourceManager.GetString("disableSqlFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 启用大写模式 的本地化字符串。
        /// </summary>
        public static string enableCapitalMode {
            get {
                return ResourceManager.GetString("enableCapitalMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 启用Kotlin 的本地化字符串。
        /// </summary>
        public static string enableKotlin {
            get {
                return ResourceManager.GetString("enableKotlin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 启用略过视图 的本地化字符串。
        /// </summary>
        public static string enableSkipView {
            get {
                return ResourceManager.GetString("enableSkipView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 启用Springdoc 的本地化字符串。
        /// </summary>
        public static string enableSpringdoc {
            get {
                return ResourceManager.GetString("enableSpringdoc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 启用Swagger 的本地化字符串。
        /// </summary>
        public static string enableSwagger {
            get {
                return ResourceManager.GetString("enableSwagger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 English 的本地化字符串。
        /// </summary>
        public static string English__United_States_ {
            get {
                return ResourceManager.GetString("English (United States)", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 领域类 的本地化字符串。
        /// </summary>
        public static string entity {
            get {
                return ResourceManager.GetString("entity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 领域类模板 的本地化字符串。
        /// </summary>
        public static string entityTemplate {
            get {
                return ResourceManager.GetString("entityTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 字段前缀 的本地化字符串。
        /// </summary>
        public static string fieldPrefix {
            get {
                return ResourceManager.GetString("fieldPrefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 字段后缀列表 的本地化字符串。
        /// </summary>
        public static string fieldSuffixList {
            get {
                return ResourceManager.GetString("fieldSuffixList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 文件覆写 的本地化字符串。
        /// </summary>
        public static string fileOverride {
            get {
                return ResourceManager.GetString("fileOverride", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 全局配置 的本地化字符串。
        /// </summary>
        public static string GlobalConfig {
            get {
                return ResourceManager.GetString("GlobalConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 包含 的本地化字符串。
        /// </summary>
        public static string include {
            get {
                return ResourceManager.GetString("include", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 注入配置 的本地化字符串。
        /// </summary>
        public static string InjectionConfig {
            get {
                return ResourceManager.GetString("InjectionConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 键 的本地化字符串。
        /// </summary>
        public static string key {
            get {
                return ResourceManager.GetString("key", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 查找类似 {0} 的本地化字符串。 的本地化字符串。
        /// </summary>
        public static string LangComment {
            get {
                return ResourceManager.GetString("LangComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 语言 的本地化字符串。
        /// </summary>
        public static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 映射器 的本地化字符串。
        /// </summary>
        public static string mapper {
            get {
                return ResourceManager.GetString("mapper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 映射器模板 的本地化字符串。
        /// </summary>
        public static string mapperTemplate {
            get {
                return ResourceManager.GetString("mapperTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 模块名称 的本地化字符串。
        /// </summary>
        public static string moduleName {
            get {
                return ResourceManager.GetString("moduleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 好的 的本地化字符串。
        /// </summary>
        public static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 输出目录 的本地化字符串。
        /// </summary>
        public static string outputDir {
            get {
                return ResourceManager.GetString("outputDir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 包配置 的本地化字符串。
        /// </summary>
        public static string PackageConfig {
            get {
                return ResourceManager.GetString("PackageConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 父类 的本地化字符串。
        /// </summary>
        public static string parent {
            get {
                return ResourceManager.GetString("parent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 密码 的本地化字符串。
        /// </summary>
        public static string password {
            get {
                return ResourceManager.GetString("password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 路径信息 的本地化字符串。
        /// </summary>
        public static string pathInfo {
            get {
                return ResourceManager.GetString("pathInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请提供配置名称 的本地化字符串。
        /// </summary>
        public static string Please_provide_config_name {
            get {
                return ResourceManager.GetString("Please provide config name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 服务接口 的本地化字符串。
        /// </summary>
        public static string service {
            get {
                return ResourceManager.GetString("service", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 服务实现类 的本地化字符串。
        /// </summary>
        public static string serviceImpl {
            get {
                return ResourceManager.GetString("serviceImpl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 服务实现模板 的本地化字符串。
        /// </summary>
        public static string serviceImplTemplate {
            get {
                return ResourceManager.GetString("serviceImplTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 服务接口模板 的本地化字符串。
        /// </summary>
        public static string serviceTemplate {
            get {
                return ResourceManager.GetString("serviceTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 策略配置 的本地化字符串。
        /// </summary>
        public static string StrategyConfig {
            get {
                return ResourceManager.GetString("StrategyConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 表前缀列表 的本地化字符串。
        /// </summary>
        public static string tablePrefixList {
            get {
                return ResourceManager.GetString("tablePrefixList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 表后缀列表 的本地化字符串。
        /// </summary>
        public static string tableSuffixList {
            get {
                return ResourceManager.GetString("tableSuffixList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 模板配置 的本地化字符串。
        /// </summary>
        public static string TemplateConfig {
            get {
                return ResourceManager.GetString("TemplateConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 类型转换 的本地化字符串。
        /// </summary>
        public static string typeConvert {
            get {
                return ResourceManager.GetString("typeConvert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 类型转换事件 的本地化字符串。
        /// </summary>
        public static string typeConvertHandler {
            get {
                return ResourceManager.GetString("typeConvertHandler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Url 的本地化字符串。
        /// </summary>
        public static string url {
            get {
                return ResourceManager.GetString("url", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用户名 的本地化字符串。
        /// </summary>
        public static string username {
            get {
                return ResourceManager.GetString("username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 值 的本地化字符串。
        /// </summary>
        public static string value {
            get {
                return ResourceManager.GetString("value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 xml文件 的本地化字符串。
        /// </summary>
        public static string xml {
            get {
                return ResourceManager.GetString("xml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Xml模板 的本地化字符串。
        /// </summary>
        public static string xmlTemplate {
            get {
                return ResourceManager.GetString("xmlTemplate", resourceCulture);
            }
        }
    }
}
